# 25.11.22

[versions]
# https://developer.android.com/reference/tools/gradle-api
# https://mvnrepository.com/artifact/com.android.tools.build/gradle
gradlePlugin = "8.13.1"
gradlePlugin-update = "9.0.0-beta02"
tools = "31.13.1" # https://mvnrepository.com/artifact/com.android.tools/sdk-common
compileSdk = "36"
compileSdkExt = "19" # Num or '-'
minSdk = "31" # https://apilevels.com/
### AndroidX
# https://developer.android.com/google/play/billing/release-notes
billing = "8.1.0"
# https://github.com/androidx/androidx
# https://developer.android.com/jetpack/androidx/versions
core = "1.17.0" # https://developer.android.com/jetpack/androidx/releases/core
activity = "1.12.0" # https://developer.android.com/jetpack/androidx/releases/activity
media3 = "1.8.0" # https://developer.android.com/jetpack/androidx/releases/media3
### Others
firebase-bom = "34.6.0" # https://firebase.google.com/support/release-notes/android


[libraries]
gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin" }
#gradlePlugin-update = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin-update" }
gradlePlugin-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "gradlePlugin" }
gradlePlugin-tools = { group = "com.android.tools", name = "sdk-common", version.ref = "tools" }
### AndroidX
billing = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
# + media3 - https://developer.android.com/jetpack/androidx/releases/media3
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3" }
media3-exoplayer-midi = { group = "androidx.media3", name = "media3-exoplayer-midi", version.ref = "media3" }
media3-exoplayer-ima = { group = "androidx.media3", name = "media3-exoplayer-ima", version.ref = "media3" }
media3-datasource-cronet = { group = "androidx.media3", name = "media3-datasource-cronet", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
media3-ui-leanback = { group = "androidx.media3", name = "media3-ui-leanback", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-extractor = { group = "androidx.media3", name = "media3-extractor", version.ref = "media3" }
media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "media3" }
media3-exoplayer-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "media3" }
media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "media3" }
media3-effect = { group = "androidx.media3", name = "media3-effect", version.ref = "media3" }
media3-muxer = { group = "androidx.media3", name = "media3-muxer", version.ref = "media3" }
media3-test-utils = { group = "androidx.media3", name = "media3-test-utils", version.ref = "media3" }
media3-test-utils-robolectric = { group = "androidx.media3", name = "media3-test-utils-robolectric", version.ref = "media3" }
media3-container = { group = "androidx.media3", name = "media3-container", version.ref = "media3" }
media3-database = { group = "androidx.media3", name = "media3-database", version.ref = "media3" }
media3-decoder = { group = "androidx.media3", name = "media3-decoder", version.ref = "media3" }
media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
### Others
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }


[bundles]
### AndroidX
compose = ["activity-compose"]
media = ["media3-exoplayer"]
media-ui = ["media3-ui-compose"]
### Others
firebase-crashlytics = ["firebase-crashlytics", "firebase-crashlytics-ndk"]

[plugins]
application = { id = "com.android.application", version.ref = "gradlePlugin" }
library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradlePlugin" }
### Others
# https://developers.google.com/android/guides/google-services-plugin
gms-googleServices = { id = "com.google.gms.google-services", version = "4.4.4" }
# https://firebase.google.com/docs/app-distribution/android/distribute-gradle
firebase-appDistribution = { id = "com.google.firebase.appdistribution", version = "5.2.0" }
# https://firebase.google.com/docs/crashlytics/get-started?platform=android
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }

