# 25.11.22

[versions]
molecule = "2.2.0" # https://github.com/cashapp/molecule
coil = "3.3.0" # https://github.com/coil-kt/coil
sketch = "4.4.0-alpha01" # https://github.com/panpf/sketch
materialkolor = "4.0.5" # https://github.com/jordond/MaterialKolor
haze = "1.7.1" # https://github.com/chrisbanes/haze


[libraries]
molecule = { group = "app.cash.molecule", name = "molecule-runtime", version.ref = "molecule" }
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-compose-core = { group = "io.coil-kt.coil3", name = "coil-compose-core" }
coil-network-cache-control = { group = "io.coil-kt.coil3", name = "coil-network-cache-control" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video" }
coil-test = { group = "io.coil-kt.coil3", name = "coil-test" }
sketch = { group = "io.github.panpf.sketch4", name = "sketch-singleton", version.ref = "sketch" }
sketch-compose = { group = "io.github.panpf.sketch4", name = "sketch-compose", version.ref = "sketch" }
sketch-compose-extensions = { group = "io.github.panpf.sketch4", name = "sketch-extensions-compose", version.ref = "sketch" }
sketch-compose-resources = { group = "io.github.panpf.sketch4", name = "sketch-extensions-compose-resources", version.ref = "sketch" }
sketch-http-ktor3 = { group = "io.github.panpf.sketch4", name = "sketch-http-ktor3", version.ref = "sketch" }
sketch-blurhash = { group = "io.github.panpf.sketch4", name = "sketch-blurhash", version.ref = "sketch" }
sketch-svg = { group = "io.github.panpf.sketch4", name = "sketch-svg", version.ref = "sketch" }
sketch-gif = { group = "io.github.panpf.sketch4", name = "sketch-animated-gif", version.ref = "sketch" }
sketch-webp = { group = "io.github.panpf.sketch4", name = "sketch-animated-webp", version.ref = "sketch" }
sketch-video-android = { group = "io.github.panpf.sketch4", name = "sketch-video", version.ref = "sketch" }
sketch-video-ffmpeg-android = { group = "io.github.panpf.sketch4", name = "sketch-video-ffmpeg", version.ref = "sketch" }
materialkolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialkolor" }
haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }


[bundles]
compose = [
    "molecule",
    "materialkolor",
    "haze", "haze-materials",
]
coil = [
    "coil",
    "coil-network-cache-control", "coil-network-ktor3",
]
coil-compose = [
    "coil-compose",
    "coil-network-cache-control", "coil-network-ktor3",
]
sketch = [
    "sketch",
    "sketch-http-ktor3",
    "sketch-blurhash",
]
sketch-compose = [
    "sketch-compose", "sketch-compose-extensions", "sketch-compose-resources",
    "sketch-http-ktor3",
    "sketch-blurhash",
]


[plugins]

