# 25.11.22

[versions]
### KMP
crestfi-kmp-shared = "0.1.0" # https://github.com/ib-fi/kmp-shared
### Android
amplitude-android = "1.22.4" # https://github.com/amplitude/Amplitude-Kotlin
facebook-android = "18.1.3" # https://github.com/facebook/facebook-android-sdk
appsFlyer-android = "6.17.5" # https://github.com/AppsFlyerSDK/appsflyer-android-sdk
### iOS
#amplitude-ios = ""
#facebook-ios = ""
#appsFlyer-ios = ""
### Others


[libraries]
### KMP
crestfi-kmp-shared = { group = "pro.crestfi.kmp", name = "shared", version.ref = "crestfi-kmp-shared" }
crestfi-kmp-compose = { group = "pro.crestfi.kmp", name = "compose", version.ref = "crestfi-kmp-shared" }
### Android
amplitude-android = { group = "com.amplitude", name = "analytics-android", version.ref = "amplitude-android" }
facebook-android = { group = "com.facebook.android", name = "facebook-core", version.ref = "facebook-android" }
appsFlyer-android = { group = "com.appsflyer", name = "af-android-sdk", version.ref = "appsFlyer-android" }
### iOS
### Others


[bundles]
### KMP
### Android
### iOS
### Others


[plugins]

