# 25.11.22
# https://repo.maven.apache.org/maven2/org/jetbrains/
# https://maven.google.com/web/index.html#androidx.compose

[versions]
# https://github.com/JetBrains/compose-multiplatform
compose = "1.10.0-rc02"
compose-material3 = "1.10.0-alpha05"
compose-material3-adaptive = "1.3.0-alpha02"
compose-lifecycle = "2.10.0-alpha06"
compose-navigation = "2.9.1"
compose-navigation3 = "1.0.0-alpha06"
compose-navigationEvent = "1.0.0-rc02"
compose-savedstate = "1.4.0"
compose-window = "1.5.1"
datastore = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/datastore
room = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/room
sqlite = "2.6.2" # https://developer.android.com/jetpack/androidx/releases/sqlite
kotlinx-datetime = "0.7.1" # https://github.com/Kotlin/kotlinx-datetime
kotlinx-serialization = "1.9.0" # https://github.com/Kotlin/kotlinx.serialization
kotlinx-collections-immutable = "0.4.0" # https://github.com/Kotlin/kotlinx.collections.immutable
ktor = "3.3.3" # https://github.com/ktorio/ktor


[libraries]
gradlePlugin-compose = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }
gradlePlugin-room = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
compose-full = { group = "org.jetbrains.compose", name = "compose-full", version.ref = "compose" }
compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose" }
compose-animation-graphics = { group = "org.jetbrains.compose.animation", name = "animation-graphics", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "compose" }
compose-material-iconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version = "1.7.3" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-adaptive-navigationSuite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "compose-material3" }
#compose-material3.adaptive-*
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-runtimeSaveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-test = { group = "org.jetbrains.compose.ui", name = "ui-test", version.ref = "compose" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose" }
compose-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-navigation3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "compose-material3-adaptive" }
compose-lifecycle = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "compose-lifecycle" }
compose-lifecycle-viewmodel-navigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "compose-lifecycle" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-navigation3 = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "compose-navigation3" }
compose-navigationEvent = { group = "org.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "compose-navigationEvent" }
compose-savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate-compose", version.ref = "compose-savedstate" }
compose-window = { group = "org.jetbrains.androidx.window", name = "window-core", version.ref = "compose-window" }
datastore = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
datastore-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
sqlite = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kotlinx-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android" }
ktor-client-drawain = { group = "io.ktor", name = "ktor-client-darwin" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf" }
ktor-serialization-kotlinx-cbor = { group = "io.ktor", name = "ktor-serialization-kotlinx-cbor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm" }
ktor-server-tests = { group = "io.ktor", name = "ktor-server-tests-jvm" }


[bundles]
compose = [
    "compose-animation", "compose-animation-graphics",
    "compose-foundation",
    "compose-material", "compose-material-iconsExtended",
    "compose-material3", "compose-material3-adaptive-navigationSuite",
    "compose-runtime", "compose-runtimeSaveable",
    "compose-ui", "compose-ui-util",
    "compose-components-resources",
    # androidx
    "compose-material3-adaptive", "compose-material3-adaptive-layout", "compose-material3-adaptive-navigation", "compose-material3-adaptive-navigation3",
    "compose-lifecycle", "compose-lifecycle-viewmodel", "compose-lifecycle-viewmodel-savedstate", "compose-lifecycle-viewmodel-navigation3",
    "compose-navigation", "compose-navigation3", "compose-navigationEvent",
    "compose-savedstate",
    "compose-window",
]
compose-preview = ["compose-ui-tooling-preview"]
compose-test = ["compose-ui-test"]
compose-android = ["compose-ui-tooling"]
datastore = ["datastore", "datastore-okio", "datastore-preferences"]
room = ["room", "sqlite"]
kotlinx = [
    "kotlinx-datetime",
#    "kotlinx-collections-immutable", # compose-runtime 에 내장되어 있음.
]
ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json", "ktor-serialization-kotlinx-protobuf",
    "ktor-client-logging",
]
ktor-android = ["ktor-client-okhttp"]
ktor-ios = ["ktor-client-drawain"]


[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
room = { id = "androidx.room", version.ref = "room" }

